# segment: node
# description: Shows Node.js version inside JS/TS projects
# elements: node_version nvm package
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION='##ICON##'
typeset -g POWERLEVEL9K_NVM_FOREGROUND=70
typeset -g POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_NVM_SHOW_SYSTEM=true
typeset -g POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_EXPANSION='##ICON##'
typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=117
typeset -g POWERLEVEL9K_PACKAGE_VISUAL_IDENTIFIER_EXPANSION='##ICON##'
